# 访问项目的端口号
server:
  port: 8080

  # 配置数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3308/shoping
    username: root
    password: 1234
    driver-class-name:  com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

  web:
    resources:
      static-locations: classPath:/templates/,classPath:/static/

# 配置mybatis
mybatis:
  mapper-locations: mapper/*.xml

# 配置前端页面
